AllCops:   
  Exclude:     
    - 'db/**/*'     
    - 'config/**/*'
    - 'bin/*'     
    - 'script/**/*'
    - 'client/**/*'

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - 'spec/**/*.rb'

Style/NegatedIf:
  EnforcedStyle: prefix
