default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: external_ruby_camp_development
  username: postgres
  host: localhost
  port: 5432
  
test:
  <<: *default
  database: external_ruby_camp_test
  username: postgres
  host: postgres
  port: 5432

production:
  <<: *default
  database: external_ruby_camp_production
  username: jnunez
  password: <%= ENV['EXTERNAL_RUBY_CAMP_PRODUCTION'] %>